-- Generated by node scripts/prepare-database.cjs
-- For the existing NSUK Events database, after its baseline schema.

-- Migration: 202609130001_account_approval.sql
-- Apply after SUPABASE_FULL_SCHEMA.sql. Review in a test Supabase project first.
begin;

alter table public.profiles add column if not exists account_status text not null default 'approved'
  check (account_status in ('approved', 'pending', 'disabled'));
alter table public.profiles add column if not exists expo_push_token text;
alter table public.notifications add column if not exists source_key text unique;

create or replace function public.is_active_account(p_user_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = p_user_id and account_status = 'approved'); $$;

-- Restrictive policies apply alongside the existing ownership/audience policies.
do $$
declare table_name text;
begin
  foreach table_name in array array['events', 'event_registrations', 'event_bookmarks', 'announcements', 'notifications', 'user_settings'] loop
    execute format('drop policy if exists approved_account_required on public.%I', table_name);
    execute format('create policy approved_account_required on public.%I as restrictive for all to authenticated using (public.is_active_account(auth.uid())) with check (public.is_active_account(auth.uid()))', table_name);
  end loop;
end;
$$;

create or replace function public.can_administer(p_user_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.admin_users a join public.profiles p on p.id = a.id
    where a.id = p_user_id and a.role in ('superadmin', 'moderator') and p.account_status = 'approved'
  );
$$;

create or replace function public.is_staff(p_user_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles p where p.id = p_user_id
    and p.account_status = 'approved'
    and (p.account_type in ('staff', 'organizer') or public.can_administer(p_user_id))
  );
$$;

-- Users can edit their personal information, but cannot approve or promote themselves.
create or replace function public.protect_profile_authority()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is not null and not public.can_administer(auth.uid()) then
    if tg_op = 'INSERT' then
      if new.account_type not in ('student', 'staff', 'organizer') then
        raise exception 'Invalid account type';
      end if;
      new.account_status := case when new.account_type = 'student' then 'approved' else 'pending' end;
    elsif new.account_type is distinct from old.account_type or new.account_status is distinct from old.account_status then
      raise exception 'Only an administrator can change account authority';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists protect_profile_authority on public.profiles;
create trigger protect_profile_authority before insert or update on public.profiles
for each row execute function public.protect_profile_authority();

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated
using (id = auth.uid() or public.can_administer(auth.uid()))
with check (id = auth.uid() or public.can_administer(auth.uid()));

drop policy if exists events_update_staff_owner on public.events;
create policy events_update_staff_owner on public.events for update to authenticated
using ((created_by = auth.uid() and public.is_staff(auth.uid())) or public.can_administer(auth.uid()))
with check ((created_by = auth.uid() and public.is_staff(auth.uid())) or public.can_administer(auth.uid()));

drop policy if exists events_delete_staff_owner on public.events;
create policy events_delete_staff_owner on public.events for delete to authenticated
using ((created_by = auth.uid() and public.is_staff(auth.uid())) or public.can_administer(auth.uid()));

drop policy if exists events_select_visible on public.events;
create policy events_select_visible on public.events for select to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.account_status = 'approved')
  and (created_by = auth.uid() or public.can_administer(auth.uid()) or
    (status = 'published' and (target_audience = 'all' or
      exists (select 1 from public.profiles p where p.id = auth.uid() and
        ((target_audience = 'students' and p.account_type = 'student') or
         (target_audience = 'staff' and p.account_type in ('staff', 'organizer', 'admin')))))))
);

-- Capacity decisions must count all RSVPs, including rows hidden from the attendee.
alter function public.handle_event_registration_rules() security definer;
alter function public.handle_event_registration_rules() set search_path = public;

drop policy if exists event_registrations_select_admin on public.event_registrations;
create policy event_registrations_select_admin on public.event_registrations for select to authenticated
using (public.can_administer(auth.uid()));

commit;


-- Migration: 202609140001_mobile_data.sql
-- Apply after 202609130001_account_approval.sql. Additive migration; preserves application records.
begin;

create table if not exists public.academic_levels (
  name text primary key,
  sort_order integer not null default 0
);
insert into public.academic_levels(name, sort_order) values
  ('100 Level', 100), ('200 Level', 200), ('300 Level', 300),
  ('400 Level', 400), ('500 Level', 500), ('600 Level', 600), ('Postgraduate', 700)
on conflict (name) do nothing;

create table if not exists public.event_categories (name text primary key);
insert into public.event_categories(name) values
  ('Seminar'), ('Workshop'), ('Sports'), ('Social'), ('Conference'), ('Academic'),
  ('Career'), ('Cultural'), ('Health'), ('Technology'), ('Community'), ('Orientation')
on conflict (name) do nothing;
insert into public.event_categories(name)
select distinct trim(category) from public.events where trim(category) <> ''
on conflict (name) do nothing;

alter table public.academic_levels enable row level security;
alter table public.event_categories enable row level security;
drop policy if exists levels_read on public.academic_levels;
create policy levels_read on public.academic_levels for select to anon, authenticated using (true);
drop policy if exists categories_read on public.event_categories;
create policy categories_read on public.event_categories for select to authenticated using (true);
grant select on public.academic_levels to anon, authenticated;
grant select on public.event_categories to authenticated;

-- Counts only: do not expose participant identities to other attendees.
-- Match event visibility explicitly because this function bypasses registration RLS.
create or replace function public.get_event_registration_counts(p_event_ids uuid[])
returns table(event_id uuid, registered_count bigint)
language plpgsql stable security definer set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_active_account(auth.uid()) then return; end if;
  if coalesce(cardinality(p_event_ids), 0) > 200 then
    raise exception 'Request at most 200 event counts at a time';
  end if;
  return query
  select e.id, count(r.id)
  from public.events e
  join public.profiles p on p.id = auth.uid()
  left join public.event_registrations r on r.event_id = e.id and r.status = 'registered'
  where e.id = any(p_event_ids)
    and (e.created_by = auth.uid() or public.can_administer(auth.uid()) or
      (e.status = 'published' and (e.target_audience = 'all' or
        (e.target_audience = 'students' and p.account_type = 'student') or
        (e.target_audience = 'staff' and p.account_type in ('staff', 'organizer', 'admin')))))
  group by e.id;
end;
$$;
revoke all on function public.get_event_registration_counts(uuid[]) from public, anon;
grant execute on function public.get_event_registration_counts(uuid[]) to authenticated;

alter table public.profiles add column if not exists expo_push_token text;
alter table public.notifications add column if not exists source_key text;
create unique index if not exists notifications_source_key_unique on public.notifications(source_key);

-- Clear only exact images previously inserted by the app as template defaults.
-- Uploaded photos, event records, accounts and registrations are preserved.
update public.profiles set avatar_url = null
where avatar_url = 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80';
update public.events set image_url = null
where image_url = 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=80';

create table if not exists public.academic_faculties (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.academic_departments (
  id uuid primary key default gen_random_uuid(),
  faculty_name text not null,
  name text unique not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_academic_departments_faculty on public.academic_departments(faculty_name);

alter table public.academic_faculties enable row level security;
alter table public.academic_departments enable row level security;

-- Public read access so any student or staff can view academic options
drop policy if exists "Public read faculties" on public.academic_faculties;
create policy "Public read faculties" on public.academic_faculties for select using (true);
drop policy if exists "Public read departments" on public.academic_departments;
create policy "Public read departments" on public.academic_departments for select using (true);

-- Initial project catalog: NSUK Faculties
insert into public.academic_faculties (name) values
  ('Faculty of Natural and Applied Sciences'),
  ('Faculty of Social Sciences'),
  ('Faculty of Arts'),
  ('Faculty of Administration'),
  ('Faculty of Law'),
  ('Faculty of Education'),
  ('Faculty of Agriculture'),
  ('Faculty of Environmental Science')
on conflict (name) do nothing;

-- Initial project catalog: NSUK Departments
insert into public.academic_departments (faculty_name, name) values
  ('Faculty of Natural and Applied Sciences', 'Computer Science'),
  ('Faculty of Natural and Applied Sciences', 'Mathematics'),
  ('Faculty of Natural and Applied Sciences', 'Physics'),
  ('Faculty of Natural and Applied Sciences', 'Chemistry'),
  ('Faculty of Natural and Applied Sciences', 'Microbiology'),
  ('Faculty of Natural and Applied Sciences', 'Biochemistry'),
  ('Faculty of Natural and Applied Sciences', 'Zoology'),
  ('Faculty of Natural and Applied Sciences', 'Botany'),
  ('Faculty of Natural and Applied Sciences', 'Geology'),
  ('Faculty of Social Sciences', 'Economics'),
  ('Faculty of Social Sciences', 'Mass Communication'),
  ('Faculty of Social Sciences', 'Political Science'),
  ('Faculty of Social Sciences', 'Sociology'),
  ('Faculty of Social Sciences', 'Psychology'),
  ('Faculty of Arts', 'English'),
  ('Faculty of Arts', 'History and International Studies'),
  ('Faculty of Arts', 'Theatre Arts'),
  ('Faculty of Arts', 'Languages and Linguistics'),
  ('Faculty of Arts', 'Religious Studies'),
  ('Faculty of Arts', 'Philosophy'),
  ('Faculty of Administration', 'Business Administration'),
  ('Faculty of Administration', 'Accounting'),
  ('Faculty of Administration', 'Public Administration'),
  ('Faculty of Administration', 'Banking and Finance'),
  ('Faculty of Law', 'Commercial Law'),
  ('Faculty of Law', 'Public Law'),
  ('Faculty of Law', 'Private Law'),
  ('Faculty of Education', 'Educational Foundations'),
  ('Faculty of Education', 'Science Education'),
  ('Faculty of Education', 'Arts Education'),
  ('Faculty of Agriculture', 'Agronomy'),
  ('Faculty of Agriculture', 'Animal Science'),
  ('Faculty of Agriculture', 'Agricultural Economics and Extension'),
  ('Faculty of Environmental Science', 'Architecture'),
  ('Faculty of Environmental Science', 'Urban and Regional Planning'),
  ('Faculty of Environmental Science', 'Geography')
on conflict (name) do nothing;


grant select on public.academic_faculties, public.academic_departments to anon, authenticated;
notify pgrst, 'reload schema';
commit;

-- Migration: 202609190001_event_end_time.sql
-- Existing timed events receive a one-hour end time as a compatibility baseline.
begin;
alter table public.events add column if not exists end_time time;
update public.events
set end_time = (start_time + interval '1 hour')::time
where start_time is not null and end_time is null;
notify pgrst, 'reload schema';
commit;
